name: Scrape and Deploy
on:
  schedule:
    - cron: '0 21 * * 3,6,0'
  workflow_dispatch:
jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
   
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
       
    - name: Install dependencies
      run: npm ci
   
    - name: Run scraper
      run: npm run update-table
   
    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
       
        # Fetch the latest changes from the remote
        git fetch origin master
       
        # Create a new branch for our changes
        git checkout -b temp-branch
       
        # Stage changes
        git add .
       
        # Commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update competition table"
          
          # Try to rebase onto master
          if git rebase origin/master; then
            # Force push the changes
            git push --force origin temp-branch:master
          else
            echo "Rebase failed. Manual intervention may be needed."
            git rebase --abort
            exit 1
          fi
        fi
    
    - name: Build React app
      run: npm run build
   
    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"